name: pain_à_la_chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-'
  pull_request:
    branches-ignore:
        - 'ga-ignore-'

env:
  MIRROR_URL: "git@github.com:Raymondbty/test_choco.git"
  EXECUTABLES: ""
  ARGS: ""

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          unnecessary_files=($(find . \( -name '*.o' -o -name '*.a' -o \
          -name '*.so' -o -name '*gcno' -o -name '*.gcda' -o -name '#*#' \
          -o -name '*~' -o -iname "*pain_au_chocolat*" -o -path *tmp/* \)))
          for i in ${unnecessary_files[@]}; do
            echo "::error file=$i,line=1,endLine=1,title=unnecessary file::$i"
          done
          if [[ -n $unnecessary_files ]]
          then
            exit 1
          else
            echo all files ok
          fi

  check_program_compilation:
    needs: check_repository_cleanliness
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - uses: actions/checkout@v3
      - id: check_program_compilation
        run: make
        timeout-minutes: 2
      - run: make clean  
      - run: |
          OIFS=$IFS
          IFS=','
          for x in $EXECUTABLES
          do
              ./$x $ARGS
            done
          IFS=$OIFS

  run_tests:
    needs: check_program_compilation
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - uses: actions/checkout@v3
      - id: run_tests
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}